### ISSUE TITLE
REST API not working on some feeds

### ISSUE THREAD

**Issue by chrowe** [adafruit/io-issues#134]
https://io.adafruit.com/chrowe/feeds/root-cellar-inside
https://io.adafruit.com/chrowe/feeds/root-cellar-outside

e.g.
REQUEST URL: `https://io.adafruit.com/api/feeds/root-cellar-inside`
RESPONSE BODY:
`{
  "error": "not found - API documentation can be found at https://learn.adafruit.com/adafruit-io"
}`

**Comment by toddtreece** [comment]
@chrowe could you give me more info about the request you are sending? are you using a client lib?

**Comment by chrowe** [comment]
For this test I just used https://io.adafruit.com/api/docs/#!/Feeds/get


Mostly I am using https://github.com/openpipekit/opk-cli--adafruit-io to add data to the feed and getting a 500 error. This is working fine on other feeds.

e.g.
```
root@pi17:/data# echo 6 | ./opk-cli--adafruit-io/push  --feed root-cellar-outside --key <removed for sharing> --verbose
6
{ feed: 'root-cellar-outside',
  key: '<removed for sharing>',
  verbose: true }
data:
6
{"feed":"root-cellar-outside","key":"<removed for sharing>","verbose":true}
doc:
{"value":"6"}
requestOptions:
{"uri":"https://io.adafruit.com/api/feeds/root-cellar-outside/data.json","method":"POST","json":{"value":"6"},"headers":{"X-AIO-KEY":"<removed for sharing>"}}
null
{"statusCode":500,"body":"500 Internal Server Error\nIf you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.","headers":{"content-type":"text/plain","transfer-encoding":"chunked","connection":"close","status":"500 Internal Server Error","x-request-id":"6167370e-b68b-42ab-89d2-afb3dfc3d624","x-runtime":"0.020213","date":"Fri, 15 Apr 2016 15:05:54 GMT","x-powered-by":"Phusion Passenger 5.0.25","server":"nginx + Phusion Passenger 5.0.25","access-control-allow-origin":"*","access-control-allow-credentials":"true","access-control-allow-methods":"GET","access-control-allow-headers":"DNT,X-AIO-Key,Accept,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type","strict-transport-security":"max-age=31536000"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"io.adafruit.com","port":443,"hostname":"io.adafruit.com","hash":null,"search":null,"query":null,"pathname":"/api/feeds/root-cellar-outside/data.json","path":"/api/feeds/root-cellar-outside/data.json","href":"https://io.adafruit.com/api/feeds/root-cellar-outside/data.json"},"method":"POST","headers":{"X-AIO-KEY":"<removed for sharing>","accept":"application/json","content-type":"application/json","content-length":13}}}
```

**Comment by toddtreece** [comment]
@chrowe this is happening because your feed is in a group, and this issue has been addressed in API v2. 

API v2 will be available after some final testing is completed next week, and it has a new set of routes that will make interaction with groups easier.

**Comment by chrowe** [comment]
This has been working fine for a while with the feed in a group. Did something change?
If I take it out of the group should it start working again?

**Comment by chrowe** [comment]
Also, I am pushing data just fine to other feed that are in a group https://io.adafruit.com/groups/24111

**Comment by chrowe** [comment]
I just removed the feeds from all groups but they still don't work.

**Comment by toddtreece** [comment]
@chrowe thanks for the additional info, and that's very strange. i'm more familiar with the mqtt portion of IO, but i'll check into it deeper.

**Comment by jwcooper** [comment]
The feeds need to be in at least one group, and they should default into your default group if removed from all groups. I'll create an internal issue to prevent removing feeds from groups entirely.

Without them being in a group, it's tough to see if the setup is correct from end-to-end. Can you add them back to at least the default group?

**Comment by chrowe** [comment]
Looks like I don't have a default group any more.
I added them back to the group they were in to begin with, https://io.adafruit.com/groups/44101

**Comment by chrowe** [comment]
I am still having this same issue.
I can create a new feed that is not in a group and it works fine but these feeds do not work

**Comment by jwcooper** [comment]
Sorry for not getting back to you on this. If this is still an issue, can you post the updated details to our forum or reply to this post? We've made a lot of changes since November to IO and it's possible your issue has been resolved. 

https://forums.adafruit.com/viewforum.php?f=56

**Comment by greed9** [comment]
Sorry to post on a seemingly dead thread, but I think i am getting exactly the same problem.

If I use the v1 API from curl, like this:

curl -H "X-AIO-Key: my-api-key-here" https://io.adafruit.com/api/groups/altitude-tracking/send.json?gps-altitude=435.039384&latitude=2841.330000&lo
ngitude=8130.919500

Data for the first feed in the group (gps-altitude), and only the first feed in the group gets updated.

But if I use the v2 API from curl, like this:

curl -H "X-AIO-Key: my-api-key-here" https://io.adafruit.com/api/v2/groups/altitude-tracking/send.json?gps-altitude=435.039384&latitude=2841.330000
&longitude=8130.919500

I get an error message:

{"error":"not found - API documentation can be found at https://io.adafruit.com/api/docs"}

Any suggestions?
