### ISSUE TITLE
bug: dashboard gauges not showing integer values

### ISSUE THREAD

**Issue by iamnohero** [adafruit/io-issues#32]
Hi,

i've made a simple dashboard (https://io.adafruit.com/fvandevijver/smarthomelink), which initially worked nicely. but when i adapted the scale of 2 gauges (temperature and humidity), it no longer displayed the integer value but only ###. When i look directly to the feeds, i see they work just fine.
Any idea how to solve this?

**Comment by jwcooper** [comment]
Looking at the data, the gauges have 3 feeds attached to them and aren't able to display the data properly. What browser are you using?

**Comment by jwcooper** [comment]
I've deployed a fix for this. To fix your gauges, you'll need  to edit them, and then deselect and select the feed they are associated with and save the block. Thanks!

**Comment by iamnohero** [comment]
i generated it originally in Safari (Mac, El Capitan beta 4), but i've also checked it on Windows 7 computers in both chrome (v44.0.2403.155) and IExplorer. they all seem to display it the same

it seemed to be solved by your fix (i removed the old gauges, and added new ones). However, when I edit them (e.g change max value, label,..) i see the same issue reappearing.

**Comment by iamnohero** [comment]
i've noticed that when i'm in edit mode and i hoover above a gauge, i says "Feed key:light", while it should be "Feed key: temperature" or "Feed key: humidity"
> it looks like it can't remember the settings of the gauge

(also i've noticed that on the gauges that doesn't work, I dont see that little white dot in the upper left corner, although i dont know what that means)
![image](https://cloud.githubusercontent.com/assets/13846079/9335170/c5736184-45d2-11e5-8f86-6878437a1857.png)

Does this give you more information about what could be wrong?

**Comment by jwcooper** [comment]
For some reason, those gauges are loading up multiple feeds behind the scenes. That causes them to not display the data properly. Can you try clearing your cache once? Edit the gauge by removing the feed, and choosing it again? I'm not able to reproduce the issue after the fix I deployed.

**Comment by iamnohero** [comment]
that doesnt seem to solve it; even when i unselect the feed (such that no feed is selected) and press create (in step3), it still shows "Feed key:light" and that feed seems to be selected the next time i edit it. I also tried to generate a new gauge, but also that does not change anything.

**Comment by iamnohero** [comment]
it indeed looks like i load multiple feeds behind the scenes; i see the same with a line chart, although you could argue there that it's a feature :) 
![image](https://cloud.githubusercontent.com/assets/13846079/9352134/28f6d0f6-465f-11e5-9c59-748c921cd644.png)
(notice the tiny green and red line, which corresponds to temperature and humidity)

**Comment by iamnohero** [comment]
i've cleared the cache in Safari and now the gauges work fine (previously i tried to clear the cache in Chrome)
(although i'm keeping the line chart with multiple feeds, it's a nice addition :)
The issue can be marked as closed imo.

Thanks for your time & effort!

**Comment by jwcooper** [comment]
Great news, thank you!

**Comment by iamnohero** [comment]
just a small addition for future references:

the issue still occurs when my arduino is publishing to my feeds, _while_ i edit the dashboard on io.adafruit.com. 
By simply (temporarily) preventing my arduino from publishing while i edit the dashboard, everything works as expected once i restart my arduino.
